name: flutter_osrm
description: A wrapper for the Open Source Routing Machine designed for Flutter
  including optional extra functionality for flutter_map
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  google_polyline_algorithm: ^3.1.0
  http: ^1.0.0
  latlong2: ^0.9.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
